require:
  - standard

plugins:
  - standard-rails

inherit_gem:
  standard: config/base.yml
  standard-rails: config/base.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/migrate/**/*"
